heracorr: 
    file_dir: '/usr2/dgorthi/HERA_Data/2458038/zen.2458038.[1-3]*.yy.HH.uv'
    cc: [84-86]
    baseline: True
    ant: 
    set: 'PAMs'
    pol: 'yy'
    chan: [0,1,2]

mycorr:
    files: # ['../data/Oct10_PAMs_nobits_11:39-12:00.cp']
           ['../data/Oct10_PAMs_11:39-13:00.cp',
            '../data/Oct10_PAMs_13:00-14:30.cp']
            #'../data/Oct10_PAMs_14:30-16:00.cp']
            #'../data/Oct10_PAMs_16:00-17:30.cp']
    cc: [84-86]
    baseline: True
    ant: 
    set: 'PAMs'
    chan: [0,1,2]

gains:
    '84': [np.exp(2j*np.pi), np.exp(2j*np.pi),   np.exp(2j*np.pi)]
    '85': [np.exp(2j*np.pi), np.exp(2j*np.pi/2), np.exp(2j*np.pi)]
    '86': [np.exp(2j*np.pi), np.exp(2j*np.pi),   np.exp(2j*np.pi)]
    '87': [np.exp(2j*np.pi), np.exp(2j*np.pi),   np.exp(2j*np.pi)]
    '52': [np.exp(2j*np.pi), np.exp(2j*np.pi),   np.exp(2j*np.pi)]
    '53': [np.exp(2j*np.pi), np.exp(2j*2*np.pi/3), np.exp(2j*np.pi)]
    '54': [np.exp(2j*np.pi), np.exp(2j*np.pi),   np.exp(2j*np.pi)]
    '55': [np.exp(2j*np.pi), np.exp(2j*np.pi),   np.exp(2j*np.pi)]
    '24': [np.exp(2j*np.pi), np.exp(2j*np.pi/6), np.exp(2j*np.pi)]
    '25': [np.exp(2j*np.pi), np.exp(2j*2*np.pi/3), np.exp(2j*np.pi)]
    '26': [np.exp(2j*np.pi), np.exp(2j*np.pi),   np.exp(2j*np.pi)]
    '27': [np.exp(2j*np.pi), np.exp(2j*np.pi),   np.exp(2j*np.pi)]
